version: '3.9'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: opsmind-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: opsmind_user
      POSTGRES_PASSWORD: opsmind_pass_dev
      POSTGRES_DB: opsmind_db
    ports:
      - "5432:5432"
    volumes:
      - opsmind_pg_data:/var/lib/postgresql/data

volumes:
  opsmind_pg_data: