package agents

import (
	"fmt"
	"strings"

	"github.com/Divyansh670/opsmind-ai/backend/internal/models"
)

// FormatFindingsComment builds a single Markdown comment summarizing all agent findings
func FormatFindingsComment(
	secResult *models.SecuritySentinelResponse,
	costResult *models.CostPredictorResponse,
	archResult *models.ArchitectureSupervisorResponse,
) string {
	var sb strings.Builder

	sb.WriteString("## 🤖 OpsMind AI — Automated Review\n\n")

	totalIssues := 0
	if secResult != nil {
		totalIssues += len(secResult.Vulnerabilities)
	}
	if archResult != nil {
		totalIssues += len(archResult.Issues)
	}

	if totalIssues == 0 && (costResult == nil || !costResult.HasDrift) {
		sb.WriteString("✅ No issues found. This PR looks good to merge.\n")
		return sb.String()
	}

	// Security section
	if secResult != nil && len(secResult.Vulnerabilities) > 0 {
		sb.WriteString("### 🔐 Security Findings\n\n")
		for _, v := range secResult.Vulnerabilities {
			emoji := severityEmoji(v.Severity)
			sb.WriteString(fmt.Sprintf("%s **%s** — `%s:%d`\n", emoji, v.Severity, v.FilePath, v.LineNumber))
			sb.WriteString(fmt.Sprintf("- **Issue:** %s\n", v.ExploitExplanation))
			if v.CWEID != "" {
				sb.WriteString(fmt.Sprintf("- **CWE:** %s\n", v.CWEID))
			}
			if v.RemediationSnippet != "" {
				sb.WriteString(fmt.Sprintf("- **Fix:** %s\n", v.RemediationSnippet))
			}
			sb.WriteString("\n")
		}
	}

	// Cost section
	if costResult != nil && costResult.HasDrift {
		sb.WriteString("### 💰 Cost Impact\n\n")
		sign := "+"
		if costResult.DriftUSD < 0 {
			sign = ""
		}
		sb.WriteString(fmt.Sprintf("**Estimated monthly drift:** %s$%.2f\n\n", sign, costResult.DriftUSD))
		sb.WriteString(fmt.Sprintf("%s\n\n", costResult.DriftExplanation))
		if len(costResult.AffectedServices) > 0 {
			sb.WriteString(fmt.Sprintf("**Affected services:** %s\n\n", strings.Join(costResult.AffectedServices, ", ")))
		}
	}

	// Architecture section
	if archResult != nil && len(archResult.Issues) > 0 {
		sb.WriteString("### 🏗️ Architecture Findings\n\n")
		for _, issue := range archResult.Issues {
			sb.WriteString(fmt.Sprintf("- `%s:%d` — %s\n", issue.FilePath, issue.LineNumber, issue.Description))
			sb.WriteString(fmt.Sprintf("  - **Suggestion:** %s\n", issue.Suggestion))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("---\n*Generated by OpsMind AI*")

	return sb.String()
}

func severityEmoji(severity string) string {
	switch severity {
	case models.SeverityCritical:
		return "🔴"
	case models.SeverityHigh:
		return "🟠"
	case models.SeverityMedium:
		return "🟡"
	case models.SeverityLow:
		return "🟢"
	default:
		return "⚪"
	}
}
